DROP DATABASE estoque;
CREATE DATABASE ESTOQUE;
USE ESTOQUE;

CREATE TABLE MATERIAL(
    ID INT NOT NULL PRIMARY KEY,
    NOME VARCHAR (50)
);

CREATE TABLE MOVIMENTACAO_MATERIAL(
    ID INT NOT NULL PRIMARY KEY,
    MOTIVO VARCHAR(50) NOT NULL,
    QUANTIDADE INT NOT NULL DEFAULT 1,
    ID_MATERIAL INT NOT NULL,
    ENTRADA_SAIDA CHAR(1) NOT NULL DEFAULT 'E',
    
    FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL(ID)
);

    INSERT INTO MATERIAL VALUES
        (1, 'ESCUDO'),
        (2, 'ESPADA'),
        (3, 'ALABARDA'),
        (4, 'MAÇA');
        
INSERT INTO MOVIMENTACAO_MATERIAL
    (ID, MOTIVO, QUANTIDADE, ID_MATERIAL, ENTRADA_SAIDA)
VALUES
    (1, 'COMPRA', 5, 1, 'E'),
    (2, 'COMPRA', 10, 2, 'E'),
    (3, 'SUBSTITUIÇÃO POR QUEBRA', 1, 1, 'S');

SELECT
    MATERIAL.NOME AS MATERIAL_NOME,
    
    MOVIMENTACAO_MATERIAL.MOTIVO,
    MOVIMENTACAO_MATERIAL.QUANTIDADE,
    MOVIMENTACAO_MATERIAL.ENTRADA_SAIDA
    FROM movimentacao_material INNER JOIN material
    ON movimentacao_material.ID_MATERIAL = material.ID; 