use oficina;
SELECT
    MECANICO.NOME AS MECANICO_NOME,
    VEICULO.PLACA AS VEICULO_PLACA,
    VEICULO.MODELO AS VEICULO_MODELO
FROM
    VEICULO INNER JOIN MECANICO
    ON VEICULO.MECANICO_ID = MECANICO.ID;
    
SELECT
	VEICULO.MARCA AS VEICULO_MARCA,
    VEICULO.MODELO AS VEICULO_MODELO,
    MECANICO.NOME AS MECANICO_NOME
FROM 
	VEICULO LEFT JOIN MECANICO
    ON VEICULO.MECANICO_ID = MECANICO.ID;
    
SELECT
	MECANICO.ID AS MECANICO_ID,
    
    MECANICO.NOME AS MECANICO_NOME,
    VEICULO.ID AS VEICULO_ID
FROM 
	VEICULO RIGHT JOIN MECANICO
    ON VEICULO.MECANICO_ID = MECANICO.ID;
    