DROP DATABASE IF EXISTS ESCOLA;
CREATE DATABASE ESCOLA;
USE ESCOLA;

CREATE TABLE AVALIACAO(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ALUNO VARCHAR(20),
    MATERIA VARCHAR(20),
    NOTA INT
);

INSERT INTO AVALIACAO
    (ALUNO, MATERIA, NOTA)
VALUES
    ('ALEXANDRE', 'BANCO DE DADOS', 10),
    ('ALEXANDRE', 'BANCO DE DADOS', 6),
    ('BRUNO', 'BANCO DE DADOS', 6),
    ('BRUNO', 'BANCO DE DADOS', 8),
   
    ('ALEXANDRE', 'FRONT END', 5),
    ('ALEXANDRE', 'FRONT END', 6),
    ('BRUNO', 'FRONT END', 5),
    ('BRUNO', 'FRONT END', 7);    
 
SELECT
    MATERIA, ALUNO,
    SUM(NOTA) AS SOMA,
    AVG(NOTA) AS MEDIA,
    CASE
        WHEN AVG(NOTA) >= 7 THEN 'APROVADO'
        ELSE 'REPROVADO'
    END AS SITUACAO
FROM
    AVALIACAO
WHERE
    ID = :ID
GROUP BY
    MATERIA, ALUNO