-- CREATE DATABASE estoque;

USE estoque;
CREATE TABLE LOCALIZACAO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO TEXT
    

);
CREATE TABLE CATEGORIAITEM(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LOCALIZACAOID INT,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO TEXT,
    FOREIGN KEY(LOCALIZACAOID) REFERENCES LOCALIZACAO(ID)
    
    
	    

);
CREATE TABLE ITEMESTOQUE(
	CATEGORIAID INT NOT NULL,
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO TEXT,
    QUANTIDADEMINIMA INT NOT NULL DEFAULT 0,
    CODIGO VARCHAR(30) NOT NULL,
    NOMEIMAGEM VARCHAR(60)
    


);