CREATE DATABASE VET;
USE VET;
CREATE TABLE PET(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    IDADE INT NOT NULL,
    RACA VARCHAR(50) NOT NULL,
    DESCRICAO TEXT NOT NULL
    );
    select * from PET;

