drop DATABASE colecao;
CREATE DATABASE COLECAO;
USE COLECAO;
CREATE table cartas(
ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(30) NOT NULL,
DESCRICAO TEXT NOT NULL,
IMAGEM_PATH TEXT NOT NULL

);

